import React from 'react'
import { Sidebar, Menu, MenuItem, useProSidebar } from "react-pro-sidebar";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import PeopleOutlinedIcon from "@mui/icons-material/PeopleOutlined";
import ContactsOutlinedIcon from "@mui/icons-material/ContactsOutlined";
import CategoryOutlinedIcon from '@mui/icons-material/CategoryOutlined';
import CalendarTodayOutlinedIcon from "@mui/icons-material/CalendarTodayOutlined";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import MenuOutlinedIcon from "@mui/icons-material/MenuOutlined";
import SideBar from '../components/SideBar';
import Background from '../assets/images/background.jpg'
import Profile from './Profile';

export default function Home({isLoggedIn=false})
{

    return (

        <div className='mt-10 bg-lockers bg-cover bg-center h-fit min-h-screen min-w-[300px] '>
            <div className='flex flex-row '>
                <i className='text-6xl max-w-[520px] leading-loose z-50 p-3 mt-5 '>One student's trash is another one's treasure </i>
                {isLoggedIn === false ? <Profile/>:null}
                <img alt="lockers" src={Background} className='w-[50%] max-w-[650px] min-w-[600px] object-contain absolute right-5' />
            </div>
            <div className='mt-16 hover:cursor-pointer flex flex-row justify-evenly text-center mb-10'>
                <i className='bg-[#94e0c7] px-3 py-1 rounded-md mr-3 hover:-translate-y-5 duration-500 ease-in-out hover:shadow-lg shadow-black'>
                    Are you moving out and want to get rid of some luggage?
                </i >
                <i className='bg-[#94e0c7] px-3 py-1 rounded-md mr-3 hover:-translate-y-5 duration-500 ease-in-out hover:shadow-lg shadow-black'>
                    Are you moving in and don't want to spend a fortune on new utensils?
                </i >
                <i className='bg-[#94e0c7] px-3 py-1 rounded-md mr-3 hover:-translate-y-5  duration-500 ease-in-out hover:shadow-lg shadow-black'>
                    Are you in the mood of thrift shopping random objects?
                </i>
            </div>
            <p className='text-center text-2xl mb-10'>Join a network of students that want to help eachother in a sustainable way! Here is  how it works:</p>
            <div className='flex flex-row justify-around'>
                <div className='flex flex-col max-w-[500px] w-[1/3] border-[#f0ab57] rounded-md border-2  mb-10 '>
                    <p className='bg-[#f0ab57] w-full rounded-b-none font-semibold px-4 py-2 text-lg text-white text-center'>If you want to give out/sell some of your belongings:</p>
                    <div className='ml-3 mt-2 text-lg'>
                        <p>1. Create an account</p>
                        <p>2. Add your items</p>
                        <p>3. Place your items in the locker assigned to you</p>
                        <p>4. Wait for money to enter your wallet!</p>
                    </div>
                </div>

                <div className='flex flex-col w-[500px] border-[#f0ab57] rounded-md border-2  mb-10 '>
                    <p className='bg-[#f0ab57] w-full rounded-b-none font-semibold px-4 py-2 text-lg text-white text-center'>If you want to take/buy some of the items:</p>
                    <div className='ml-3 mt-2 text-lg'>
                        <p>1. Create an account</p>
                        <p>2. Select your products</p>
                        <p>3. Go to the relevant locker with the pin generated by your wallet and go home with goodies! </p>

                        <p>5. Enjoy your new items!</p>
                    </div>

                </div>
            </div>

        </div>
    )

}